### ISSUE TITLE
uninstall on localhost not working

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#11]
tried uninstalling, showed it was uninstalled in logs
https://prnt.sc/p8gemm
but software on  software  page its still installed
https://prnt.sc/p8gg5d

**Comment by Johannes2306** [comment]
To add to that, the task itself completes successfully, but the running process is never killed.
This is localhost specific issue, for you can still uninstall software on remote servers.

**Comment by notdls** [comment]
This should be fixed now, was caused by a previous bug
