### ISSUE TITLE
profile bug

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#13]
when clicking players profile
https://prnt.sc/p8gm35

**Comment by NoahCardoza** [comment]
This has to do with the profile_generator.py script not running. On the beta server, works like a charm locally though.

**Comment by bobokev** [comment]
works ok checking others profile but when i check my own  get this error
https://prnt.sc/paiq39

**Comment by notdls** [comment]
Yeah its because the others were manually generated, ill fix this sometime today.

**Comment by notdls** [comment]
fixed
