### ISSUE TITLE
Same error on multiple pages

### ISSUE THREAD

**Issue by Johannes2306** [NoahCardoza/HE-REvived-Issue-Tracker#21]
>**Location:**
Provided alongside pictures

```
SELECT COUNT(*) AS total, SUM(cpu) AS cpu, SUM(hdd) AS hdd, SUM(ram) AS ram, net FROM hardware WHERE hardware.userID = 3 AND isNPC = 0

SELECT COUNT(*) AS total, SUM(cpu) AS cpu, SUM(hdd) AS hdd, SUM(ram) AS ram, net FROM hardware WHERE hardware.userID = 3 AND isNPC = 0 SELECT COUNT(*) AS total, SUM(cpu) AS cpu, SUM(hdd) AS hdd, SUM(ram) AS ram, net FROM hardware WHERE hardware.userID = 214 AND isNPC = 1
```
**Control Panel / Home**
![image](https://user-images.githubusercontent.com/15631661/65423818-a88b7480-de12-11e9-8a66-e794881c7e99.png)

**Software**
![image](https://user-images.githubusercontent.com/15631661/65423885-d2dd3200-de12-11e9-879e-95f3204487eb.png)

**External Hard Drive**
![image](https://user-images.githubusercontent.com/15631661/65423939-f7d1a500-de12-11e9-90e1-086dfeb726e9.png)

**Hardware**
![image](https://user-images.githubusercontent.com/15631661/65423856-c3f67f80-de12-11e9-9e2b-b43bcea49c76.png)

**Task Manager**
![image](https://user-images.githubusercontent.com/15631661/65423786-990c2b80-de12-11e9-9e97-6f8d420f441b.png)

**NPC Software**
![image](https://user-images.githubusercontent.com/15631661/65424080-526b0100-de13-11e9-8901-4ffe333d5906.png)

**NPC Upload Software**
![image](https://user-images.githubusercontent.com/15631661/65424123-6b73b200-de13-11e9-976f-38aab252e380.png)

**Same error shown on localhost tasks and remote tasks**
![image](https://user-images.githubusercontent.com/15631661/65424218-a37af500-de13-11e9-92a2-1db1c3eda254.png)

**Comment by NoahCardoza** [comment]
@notdls

**Comment by NoahCardoza** [comment]
This was probably broken by @notdls while he was debugging and should be fixed.

If the problem persists, feel free to reopen this issue.
