### ISSUE TITLE
hardware not registered

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#23]
when trying to hack get this error 
https://prnt.sc/pa0cd3

**Comment by notdls** [comment]
This could've been due to me debugging the hdr/skr bug, are you getting this on all IPs or just some?

**Comment by NoahCardoza** [comment]
I'm 99% sure it has to do with the echoing of SQL queries that would break the process view and it seems to be working fine on my end.

If you see this issue again add a comment below.

**Comment by NoahCardoza** [comment]
Well, tried to hack the NSA on the live beta and got the same error... Tried it locally and it worked just fine.

I think this is a db issue on the live beta. A reset should fix it.

**Comment by Johannes2306** [comment]
Still broken

![image](https://user-images.githubusercontent.com/15631661/65495025-aaab0d00-debe-11e9-8678-4842744c8e83.png)

**Comment by notdls** [comment]
Was fixed after the db reset
