### ISSUE TITLE
All-Time Stats button not working

### ISSUE THREAD

**Issue by NoahCardoza** [NoahCardoza/HE-REvived-Issue-Tracker#25]
On the profile page:
![image](https://user-images.githubusercontent.com/10343470/65558270-e956bc80-deea-11e9-81b6-91bc49962f27.png)

Seems as if it is supposed to submit a `<form/>` but none show on the page.
![image](https://user-images.githubusercontent.com/10343470/65558317-0c816c00-deeb-11e9-99bb-9357b0293af0.png)

@notdls I'm wondering if this was never implemented in this copy of the game? Maybe we could just disable it for now?

**Comment by notdls** [comment]
Yeah I'm pretty sure this was never a thing, disable it for now

**Comment by notdls** [comment]
Fixed
