### ISSUE TITLE
Software ranking

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#26]
https://prnt.sc/pakahg
when viewing type

**Comment by NoahCardoza** [comment]
Interesting... locally it looks like...

![image](https://user-images.githubusercontent.com/10343470/65563371-355f2c80-defe-11e9-96b2-4e66909d5761.png)

**Comment by NoahCardoza** [comment]
> https://prnt.sc/pakahg
> when viewing type

It looks like the only way you would have gotten that would have been sending invalid get parameters. 

@bobokev What did you click to get to that page?

It seems to be working for me right now (on the beta).

**Comment by NoahCardoza** [comment]
I fixed the header error, but as to why you got it I still have no idea.
