### ISSUE TITLE
Server statistics

### ISSUE THREAD

**Issue by Johannes2306** [NoahCardoza/HE-REvived-Issue-Tracker#29]
>**Location:** 
`/stats?show=server`

>**Issue:**
The whole page seems to malfunction by not showing profile name, IP, online users, statistics themselves etc.

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/template/contentStart.php:1110) in /var/www/classes/System.class.php on line 335
```

![image](https://user-images.githubusercontent.com/15631661/65583615-33da4680-df88-11e9-98da-35b3f4aea794.png)

**Comment by Johannes2306** [comment]
Same issue is present on the `/stats.php?show=forum` page.
I'm pretty sure that this page can be completely scrapped though, for there isn't any forum connected to the game anymore.

**Comment by notdls** [comment]
Those two pages (forum and server) were never implemented, going to just remove them for now.

**Comment by notdls** [comment]
functionality has now been removed/disabled.
