### ISSUE TITLE
new internet page error

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#31]
first time i have got this error
https://prnt.sc/paw1z7

**Comment by NoahCardoza** [comment]
I was also getting this error. I think it was @notdls breaking stuff again 😂. Honestly not sure why it’s not working. I might be able to take a look before work but not sure.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bobokev** [comment]
seems to have same issue on a few pages 
https://prnt.sc/paw6eo

**Comment by notdls** [comment]
Ah yeah i guess my new json cookies is having some issues, will look into this in a bit

**Comment by notdls** [comment]
Pretty sure this was caused by having still having the previous style cookies stored in your browser, if you're still getting the error try clearing your cookies and trying again. if the problem persists feel free to re-open.
