### ISSUE TITLE
downloading by id bug

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#39]
i just became an npc
https://prnt.sc/pbw2fl
you can even download puzzle exe by id
from anywhere i can edit download by id and get every software in the game
https://prnt.sc/pbw4fu 
also the bug where stack process then delete them still works downloaded everything in seconds
https://prnt.sc/pbwa4v
https://prnt.sc/pbwck5      lulz
https://prnt.sc/pbwu0a can even research it

**Comment by NoahCardoza** [comment]
Issue for the download by id #40

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by notdls** [comment]
this should be fixed.
