### ISSUE TITLE
problem with clans 

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#45]
nothing shows for clan admin
tried to upload a file got this error https://prnt.sc/pev4rn
https://prnt.sc/pev6bv

**Comment by notdls** [comment]
can't seem to reproduce that first error, but that second one has been fixed, just need a new round to regenerate the logs/web server content.

**Comment by NoahCardoza** [comment]
It’s probably due to requiring the PDO DB file twice... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by notdls** [comment]
should be fixed now
