### ISSUE TITLE
Software on npc's doubling up

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#5]
all npc's
https://prnt.sc/p7xt3m

**Comment by NoahCardoza** [comment]
Is that the first mission you did on that npc? Or had you already ran a mission on it before?

**Comment by notdls** [comment]
Not related to missions for me, even dl center and 1st whois are doubling up

**Comment by NoahCardoza** [comment]
I’m guessing it might ah e to do with the npc software reset script, maybe another script was deleting? And running it faster is causing them to double up sometimes? Either that or there is just a plain error in the npc reset script

**Comment by Johannes2306** [comment]
Issue is still present

![image](https://user-images.githubusercontent.com/15631661/65287275-44835a80-db4b-11e9-88e2-45909913182a.png)

**Comment by NoahCardoza** [comment]
Is this still an issue? I don't see doubles on my local copy.

**Comment by Johannes2306** [comment]
> Is this still an issue? I don't see doubles on my local copy.

Yes the issue still seems to exist on the server
![image](https://user-images.githubusercontent.com/15631661/65495369-53f20300-debf-11e9-8c3b-140d6f443ccf.png)

**Comment by NoahCardoza** [comment]
Doesn't seem to be an issue after the db reset.

+ NSA
  + ![image](https://user-images.githubusercontent.com/10343470/65559959-9a605580-def1-11e9-9060-a420e152e324.png)
+ Second Whois
  + ![image](https://user-images.githubusercontent.com/10343470/65560074-15c20700-def2-11e9-8799-88f1dd6c1423.png)
