### ISSUE TITLE
RAM bug

### ISSUE THREAD

**Issue by bobokev** [NoahCardoza/HE-REvived-Issue-Tracker#7]
https://prnt.sc/p7yti0
wont let me install and i have 
12288
MB ram ram has always had an issue i am sure it was best to not buy any at all

**Comment by NoahCardoza** [comment]
Weird thing is I remember ram not even mattering, still we should fix that, but I remember not needing to buy ram

**Comment by notdls** [comment]
Wait, is that errir showing when you try to run the virus on the victim?

**Comment by NoahCardoza** [comment]
Wait, could it be the npc’s server doesn’t have enough? Because running remote software should use up your ram.

**Comment by bobokev** [comment]
its not the victim  50 Mbit ( 6.25MB/s - 3.13MB/s)

**Comment by bobokev** [comment]
Think i figured it has to do with my ram usage   https://prnt.sc/p7yzqt
https://prnt.sc/p7z0f9

**Comment by bobokev** [comment]
if you notice on that last screen shot still a bug where downloaded software does not 
 use any  at all

**Comment by NoahCardoza** [comment]
This might be fixed with the db reset. If it comes up again let us know.
