### ISSUE TITLE
NPC hardware resets use static values for all servers instead of going back to their original state

### ISSUE THREAD

**Issue by notdls** [NoahCardoza/HE-REvived-Issue-Tracker#8]
Title, leads to some servers haveing software that dont on their servers, also some servers having the wrong internet speed, e.g. NSA goes down from 1gbit to 50mbps

**Comment by NoahCardoza** [comment]
Still needs to be tested

**Comment by NoahCardoza** [comment]
This bug has been fixed, but still needs to be tested. Mind you DLS will have to update before you will notice the changes.
